apps:
  mkwineprefix:
    command: 'bin/mkwineprefix'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
description: 'Create a Wine prefix with custom settings.'
grade: 'stable'
name: 'mkwineprefix'
parts:
  mkwineprefix:
    plugin: 'poetry'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
summary: 'Create a Wine prefix with custom settings.'
version: '0.0.0'
