apps:
  mkwineprefix:
    command: 'bin/mkwineprefix'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/mkwineprefix/issues'
description: 'Create a Wine prefix with custom settings.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/mkwineprefix/issues'
license: 'MIT'
name: 'mkwineprefix'
parts:
  mkwineprefix:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/mkwineprefix'
summary: 'Create a Wine prefix with custom settings.'
title: 'mkwineprefix'
version: '0.0.1'
website: 'https://tatsh.github.io/mkwineprefix/'
